create database roadwolf;

CREATE TABLE `COURSE` (
  `COURSE_ID` int(11) NOT NULL AUTO_INCREMENT,
  `OPERATOR_ID` int(11) NOT NULL,
  `CITY_DEPARTURE_ID` int(11) NOT NULL,
  `CITY_ARRIVAL_ID` int(11) NOT NULL,
  `ARRIVAL_TIME` varchar(15) NOT NULL,
  `DEPARTURE_TIME` varchar(15) NOT NULL,
  `STOP_LIST` varchar(200) NOT NULL,
  `SYMBOLS` varchar(200) NOT NULL,
  PRIMARY KEY (`COURSE_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8

CREATE TABLE `STOP` (
  `STOP_ID` int(11) NOT NULL AUTO_INCREMENT,
  `COURSE_ID` int(11) NOT NULL,
  `CITY_ID` int(11) NOT NULL,
  `ARRIVAL_TIME` varchar(15) NOT NULL,
  `DEPARTURE_TIME` varchar(15) NOT NULL,

  PRIMARY KEY (`STOP_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8

CREATE TABLE `OPERATOR` (
  `OPERATOR_ID` int(11) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(200) NOT NULL,
  `DESCRIPTION` varchar(200) NOT NULL,

  PRIMARY KEY (`OPERATOR_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8

CREATE TABLE `CITY` (
  `CITY_ID` int(11) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(200) NOT NULL,
  `VOIOVODESHIP` varchar(200) NOT NULL,
  `DISTRICT` varchar(200) NOT NULL,
  PRIMARY KEY (`CITY_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8

